'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="dev")>  _
Partial Public Class Asr5500ChkSheetDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "拡張メソッドの定義"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub Insertasr5500_chksheets(instance As asr5500_chksheets)
    End Sub
  Partial Private Sub Updateasr5500_chksheets(instance As asr5500_chksheets)
    End Sub
  Partial Private Sub Deleteasr5500_chksheets(instance As asr5500_chksheets)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("devConnectionString1").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property asr5500_chksheets() As System.Data.Linq.Table(Of asr5500_chksheets)
		Get
			Return Me.GetTable(Of asr5500_chksheets)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.asr5500_chksheets")>  _
Partial Public Class asr5500_chksheets
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _id As Integer
	
	Private _date As System.Nullable(Of Date)
	
	Private _no1 As System.Nullable(Of Boolean)
	
	Private _no2 As System.Nullable(Of Boolean)
	
	Private _no3 As System.Nullable(Of Boolean)
	
	Private _no4 As System.Nullable(Of Boolean)
	
	Private _no5 As System.Nullable(Of Boolean)
	
	Private _no6 As System.Nullable(Of Boolean)
	
	Private _no7 As System.Nullable(Of Boolean)
	
	Private _no8 As System.Nullable(Of Boolean)
	
	Private _no9 As System.Nullable(Of Boolean)
	
	Private _no10 As System.Nullable(Of Boolean)
	
	Private _no11 As System.Nullable(Of Boolean)
	
	Private _no12 As System.Nullable(Of Boolean)
	
	Private _no13 As System.Nullable(Of Boolean)
	
	Private _no14 As System.Nullable(Of Boolean)
	
	Private _no15 As System.Nullable(Of Boolean)
	
	Private _no16 As System.Nullable(Of Boolean)
	
	Private _no17 As System.Nullable(Of Boolean)
	
	Private _no18 As System.Nullable(Of Boolean)
	
	Private _no19 As System.Nullable(Of Boolean)
	
	Private _no20 As System.Nullable(Of Boolean)
	
	Private _no21 As System.Nullable(Of Boolean)
	
	Private _no22 As System.Nullable(Of Boolean)
	
	Private _no23 As System.Nullable(Of Boolean)
	
	Private _no24 As System.Nullable(Of Boolean)
	
	Private _no25 As System.Nullable(Of Boolean)
	
	Private _no26 As System.Nullable(Of Boolean)
	
	Private _no27 As System.Nullable(Of Boolean)
	
	Private _no28 As System.Nullable(Of Boolean)
	
	Private _no29 As System.Nullable(Of Boolean)
	
	Private _no30 As System.Nullable(Of Boolean)
	
	Private _no31 As System.Nullable(Of Boolean)
	
	Private _no32 As System.Nullable(Of Boolean)
	
	Private _no33 As System.Nullable(Of Boolean)
	
	Private _no34 As System.Nullable(Of Boolean)
	
	Private _no35 As System.Nullable(Of Boolean)
	
	Private _no36 As System.Nullable(Of Boolean)
	
	Private _no37 As System.Nullable(Of Boolean)
	
	Private _no38 As System.Nullable(Of Boolean)
	
	Private _no39 As System.Nullable(Of Boolean)
	
	Private _no40 As System.Nullable(Of Boolean)
	
	Private _no1_dblchk As System.Nullable(Of Boolean)
	
	Private _no2_dblchk As System.Nullable(Of Boolean)
	
	Private _no3_dblchk As System.Nullable(Of Boolean)
	
	Private _no4_dblchk As System.Nullable(Of Boolean)
	
	Private _no5_dblchk As System.Nullable(Of Boolean)
	
	Private _no6_dblchk As System.Nullable(Of Boolean)
	
	Private _no7_dblchk As System.Nullable(Of Boolean)
	
	Private _no8_dblchk As System.Nullable(Of Boolean)
	
	Private _no9_dblchk As System.Nullable(Of Boolean)
	
	Private _no10_dblchk As System.Nullable(Of Boolean)
	
	Private _no11_dblchk As System.Nullable(Of Boolean)
	
	Private _no12_dblchk As System.Nullable(Of Boolean)
	
	Private _no13_dblchk As System.Nullable(Of Boolean)
	
	Private _no14_dblchk As System.Nullable(Of Boolean)
	
	Private _no15_dblchk As System.Nullable(Of Boolean)
	
	Private _no16_dblchk As System.Nullable(Of Boolean)
	
	Private _no17_dblchk As System.Nullable(Of Boolean)
	
	Private _no18_dblchk As System.Nullable(Of Boolean)
	
	Private _no19_dblchk As System.Nullable(Of Boolean)
	
	Private _no20_dblchk As System.Nullable(Of Boolean)
	
	Private _no21_dblchk As System.Nullable(Of Boolean)
	
	Private _no22_dblchk As System.Nullable(Of Boolean)
	
	Private _no23_dblchk As System.Nullable(Of Boolean)
	
	Private _no24_dblchk As System.Nullable(Of Boolean)
	
	Private _no25_dblchk As System.Nullable(Of Boolean)
	
	Private _no26_dblchk As System.Nullable(Of Boolean)
	
	Private _no27_dblchk As System.Nullable(Of Boolean)
	
	Private _no28_dblchk As System.Nullable(Of Boolean)
	
	Private _no29_dblchk As System.Nullable(Of Boolean)
	
	Private _no30_dblchk As System.Nullable(Of Boolean)
	
	Private _no31_dblchk As System.Nullable(Of Boolean)
	
	Private _no32_dblchk As System.Nullable(Of Boolean)
	
	Private _no33_dblchk As System.Nullable(Of Boolean)
	
	Private _no34_dblchk As System.Nullable(Of Boolean)
	
	Private _no35_dblchk As System.Nullable(Of Boolean)
	
	Private _no36_dblchk As System.Nullable(Of Boolean)
	
	Private _no37_dblchk As System.Nullable(Of Boolean)
	
	Private _no38_dblchk As System.Nullable(Of Boolean)
	
	Private _no39_dblchk As System.Nullable(Of Boolean)
	
	Private _no40_dblchk As System.Nullable(Of Boolean)
	
	Private _name1 As String
	
	Private _name2 As String
	
    #Region "拡張メソッドの定義"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnidChanging(value As Integer)
    End Sub
    Partial Private Sub OnidChanged()
    End Sub
    Partial Private Sub OndateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OndateChanged()
    End Sub
    Partial Private Sub Onno1Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno1Changed()
    End Sub
    Partial Private Sub Onno2Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno2Changed()
    End Sub
    Partial Private Sub Onno3Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno3Changed()
    End Sub
    Partial Private Sub Onno4Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno4Changed()
    End Sub
    Partial Private Sub Onno5Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno5Changed()
    End Sub
    Partial Private Sub Onno6Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno6Changed()
    End Sub
    Partial Private Sub Onno7Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno7Changed()
    End Sub
    Partial Private Sub Onno8Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno8Changed()
    End Sub
    Partial Private Sub Onno9Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno9Changed()
    End Sub
    Partial Private Sub Onno10Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno10Changed()
    End Sub
    Partial Private Sub Onno11Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno11Changed()
    End Sub
    Partial Private Sub Onno12Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno12Changed()
    End Sub
    Partial Private Sub Onno13Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno13Changed()
    End Sub
    Partial Private Sub Onno14Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno14Changed()
    End Sub
    Partial Private Sub Onno15Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno15Changed()
    End Sub
    Partial Private Sub Onno16Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno16Changed()
    End Sub
    Partial Private Sub Onno17Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno17Changed()
    End Sub
    Partial Private Sub Onno18Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno18Changed()
    End Sub
    Partial Private Sub Onno19Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno19Changed()
    End Sub
    Partial Private Sub Onno20Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno20Changed()
    End Sub
    Partial Private Sub Onno21Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno21Changed()
    End Sub
    Partial Private Sub Onno22Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno22Changed()
    End Sub
    Partial Private Sub Onno23Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno23Changed()
    End Sub
    Partial Private Sub Onno24Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno24Changed()
    End Sub
    Partial Private Sub Onno25Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno25Changed()
    End Sub
    Partial Private Sub Onno26Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno26Changed()
    End Sub
    Partial Private Sub Onno27Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno27Changed()
    End Sub
    Partial Private Sub Onno28Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno28Changed()
    End Sub
    Partial Private Sub Onno29Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno29Changed()
    End Sub
    Partial Private Sub Onno30Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno30Changed()
    End Sub
    Partial Private Sub Onno31Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno31Changed()
    End Sub
    Partial Private Sub Onno32Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno32Changed()
    End Sub
    Partial Private Sub Onno33Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno33Changed()
    End Sub
    Partial Private Sub Onno34Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno34Changed()
    End Sub
    Partial Private Sub Onno35Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno35Changed()
    End Sub
    Partial Private Sub Onno36Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno36Changed()
    End Sub
    Partial Private Sub Onno37Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno37Changed()
    End Sub
    Partial Private Sub Onno38Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno38Changed()
    End Sub
    Partial Private Sub Onno39Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno39Changed()
    End Sub
    Partial Private Sub Onno40Changing(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno40Changed()
    End Sub
    Partial Private Sub Onno1_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno1_dblchkChanged()
    End Sub
    Partial Private Sub Onno2_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno2_dblchkChanged()
    End Sub
    Partial Private Sub Onno3_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno3_dblchkChanged()
    End Sub
    Partial Private Sub Onno4_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno4_dblchkChanged()
    End Sub
    Partial Private Sub Onno5_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno5_dblchkChanged()
    End Sub
    Partial Private Sub Onno6_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno6_dblchkChanged()
    End Sub
    Partial Private Sub Onno7_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno7_dblchkChanged()
    End Sub
    Partial Private Sub Onno8_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno8_dblchkChanged()
    End Sub
    Partial Private Sub Onno9_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno9_dblchkChanged()
    End Sub
    Partial Private Sub Onno10_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno10_dblchkChanged()
    End Sub
    Partial Private Sub Onno11_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno11_dblchkChanged()
    End Sub
    Partial Private Sub Onno12_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno12_dblchkChanged()
    End Sub
    Partial Private Sub Onno13_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno13_dblchkChanged()
    End Sub
    Partial Private Sub Onno14_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno14_dblchkChanged()
    End Sub
    Partial Private Sub Onno15_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno15_dblchkChanged()
    End Sub
    Partial Private Sub Onno16_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno16_dblchkChanged()
    End Sub
    Partial Private Sub Onno17_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno17_dblchkChanged()
    End Sub
    Partial Private Sub Onno18_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno18_dblchkChanged()
    End Sub
    Partial Private Sub Onno19_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno19_dblchkChanged()
    End Sub
    Partial Private Sub Onno20_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno20_dblchkChanged()
    End Sub
    Partial Private Sub Onno21_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno21_dblchkChanged()
    End Sub
    Partial Private Sub Onno22_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno22_dblchkChanged()
    End Sub
    Partial Private Sub Onno23_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno23_dblchkChanged()
    End Sub
    Partial Private Sub Onno24_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno24_dblchkChanged()
    End Sub
    Partial Private Sub Onno25_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno25_dblchkChanged()
    End Sub
    Partial Private Sub Onno26_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno26_dblchkChanged()
    End Sub
    Partial Private Sub Onno27_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno27_dblchkChanged()
    End Sub
    Partial Private Sub Onno28_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno28_dblchkChanged()
    End Sub
    Partial Private Sub Onno29_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno29_dblchkChanged()
    End Sub
    Partial Private Sub Onno30_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno30_dblchkChanged()
    End Sub
    Partial Private Sub Onno31_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno31_dblchkChanged()
    End Sub
    Partial Private Sub Onno32_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno32_dblchkChanged()
    End Sub
    Partial Private Sub Onno33_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno33_dblchkChanged()
    End Sub
    Partial Private Sub Onno34_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno34_dblchkChanged()
    End Sub
    Partial Private Sub Onno35_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno35_dblchkChanged()
    End Sub
    Partial Private Sub Onno36_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno36_dblchkChanged()
    End Sub
    Partial Private Sub Onno37_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno37_dblchkChanged()
    End Sub
    Partial Private Sub Onno38_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno38_dblchkChanged()
    End Sub
    Partial Private Sub Onno39_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno39_dblchkChanged()
    End Sub
    Partial Private Sub Onno40_dblchkChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onno40_dblchkChanged()
    End Sub
    Partial Private Sub Onname1Changing(value As String)
    End Sub
    Partial Private Sub Onname1Changed()
    End Sub
    Partial Private Sub Onname2Changing(value As String)
    End Sub
    Partial Private Sub Onname2Changed()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property id() As Integer
		Get
			Return Me._id
		End Get
		Set
			If ((Me._id = value)  _
						= false) Then
				Me.OnidChanging(value)
				Me.SendPropertyChanging
				Me._id = value
				Me.SendPropertyChanged("id")
				Me.OnidChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="date", Storage:="_date", DbType:="Date")>  _
	Public Property [date]() As System.Nullable(Of Date)
		Get
			Return Me._date
		End Get
		Set
			If (Me._date.Equals(value) = false) Then
				Me.OndateChanging(value)
				Me.SendPropertyChanging
				Me._date = value
				Me.SendPropertyChanged("[date]")
				Me.OndateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no1", DbType:="Bit")>  _
	Public Property no1() As System.Nullable(Of Boolean)
		Get
			Return Me._no1
		End Get
		Set
			If (Me._no1.Equals(value) = false) Then
				Me.Onno1Changing(value)
				Me.SendPropertyChanging
				Me._no1 = value
				Me.SendPropertyChanged("no1")
				Me.Onno1Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no2", DbType:="Bit")>  _
	Public Property no2() As System.Nullable(Of Boolean)
		Get
			Return Me._no2
		End Get
		Set
			If (Me._no2.Equals(value) = false) Then
				Me.Onno2Changing(value)
				Me.SendPropertyChanging
				Me._no2 = value
				Me.SendPropertyChanged("no2")
				Me.Onno2Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no3", DbType:="Bit")>  _
	Public Property no3() As System.Nullable(Of Boolean)
		Get
			Return Me._no3
		End Get
		Set
			If (Me._no3.Equals(value) = false) Then
				Me.Onno3Changing(value)
				Me.SendPropertyChanging
				Me._no3 = value
				Me.SendPropertyChanged("no3")
				Me.Onno3Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no4", DbType:="Bit")>  _
	Public Property no4() As System.Nullable(Of Boolean)
		Get
			Return Me._no4
		End Get
		Set
			If (Me._no4.Equals(value) = false) Then
				Me.Onno4Changing(value)
				Me.SendPropertyChanging
				Me._no4 = value
				Me.SendPropertyChanged("no4")
				Me.Onno4Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no5", DbType:="Bit")>  _
	Public Property no5() As System.Nullable(Of Boolean)
		Get
			Return Me._no5
		End Get
		Set
			If (Me._no5.Equals(value) = false) Then
				Me.Onno5Changing(value)
				Me.SendPropertyChanging
				Me._no5 = value
				Me.SendPropertyChanged("no5")
				Me.Onno5Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no6", DbType:="Bit")>  _
	Public Property no6() As System.Nullable(Of Boolean)
		Get
			Return Me._no6
		End Get
		Set
			If (Me._no6.Equals(value) = false) Then
				Me.Onno6Changing(value)
				Me.SendPropertyChanging
				Me._no6 = value
				Me.SendPropertyChanged("no6")
				Me.Onno6Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no7", DbType:="Bit")>  _
	Public Property no7() As System.Nullable(Of Boolean)
		Get
			Return Me._no7
		End Get
		Set
			If (Me._no7.Equals(value) = false) Then
				Me.Onno7Changing(value)
				Me.SendPropertyChanging
				Me._no7 = value
				Me.SendPropertyChanged("no7")
				Me.Onno7Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no8", DbType:="Bit")>  _
	Public Property no8() As System.Nullable(Of Boolean)
		Get
			Return Me._no8
		End Get
		Set
			If (Me._no8.Equals(value) = false) Then
				Me.Onno8Changing(value)
				Me.SendPropertyChanging
				Me._no8 = value
				Me.SendPropertyChanged("no8")
				Me.Onno8Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no9", DbType:="Bit")>  _
	Public Property no9() As System.Nullable(Of Boolean)
		Get
			Return Me._no9
		End Get
		Set
			If (Me._no9.Equals(value) = false) Then
				Me.Onno9Changing(value)
				Me.SendPropertyChanging
				Me._no9 = value
				Me.SendPropertyChanged("no9")
				Me.Onno9Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no10", DbType:="Bit")>  _
	Public Property no10() As System.Nullable(Of Boolean)
		Get
			Return Me._no10
		End Get
		Set
			If (Me._no10.Equals(value) = false) Then
				Me.Onno10Changing(value)
				Me.SendPropertyChanging
				Me._no10 = value
				Me.SendPropertyChanged("no10")
				Me.Onno10Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no11", DbType:="Bit")>  _
	Public Property no11() As System.Nullable(Of Boolean)
		Get
			Return Me._no11
		End Get
		Set
			If (Me._no11.Equals(value) = false) Then
				Me.Onno11Changing(value)
				Me.SendPropertyChanging
				Me._no11 = value
				Me.SendPropertyChanged("no11")
				Me.Onno11Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no12", DbType:="Bit")>  _
	Public Property no12() As System.Nullable(Of Boolean)
		Get
			Return Me._no12
		End Get
		Set
			If (Me._no12.Equals(value) = false) Then
				Me.Onno12Changing(value)
				Me.SendPropertyChanging
				Me._no12 = value
				Me.SendPropertyChanged("no12")
				Me.Onno12Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no13", DbType:="Bit")>  _
	Public Property no13() As System.Nullable(Of Boolean)
		Get
			Return Me._no13
		End Get
		Set
			If (Me._no13.Equals(value) = false) Then
				Me.Onno13Changing(value)
				Me.SendPropertyChanging
				Me._no13 = value
				Me.SendPropertyChanged("no13")
				Me.Onno13Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no14", DbType:="Bit")>  _
	Public Property no14() As System.Nullable(Of Boolean)
		Get
			Return Me._no14
		End Get
		Set
			If (Me._no14.Equals(value) = false) Then
				Me.Onno14Changing(value)
				Me.SendPropertyChanging
				Me._no14 = value
				Me.SendPropertyChanged("no14")
				Me.Onno14Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no15", DbType:="Bit")>  _
	Public Property no15() As System.Nullable(Of Boolean)
		Get
			Return Me._no15
		End Get
		Set
			If (Me._no15.Equals(value) = false) Then
				Me.Onno15Changing(value)
				Me.SendPropertyChanging
				Me._no15 = value
				Me.SendPropertyChanged("no15")
				Me.Onno15Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no16", DbType:="Bit")>  _
	Public Property no16() As System.Nullable(Of Boolean)
		Get
			Return Me._no16
		End Get
		Set
			If (Me._no16.Equals(value) = false) Then
				Me.Onno16Changing(value)
				Me.SendPropertyChanging
				Me._no16 = value
				Me.SendPropertyChanged("no16")
				Me.Onno16Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no17", DbType:="Bit")>  _
	Public Property no17() As System.Nullable(Of Boolean)
		Get
			Return Me._no17
		End Get
		Set
			If (Me._no17.Equals(value) = false) Then
				Me.Onno17Changing(value)
				Me.SendPropertyChanging
				Me._no17 = value
				Me.SendPropertyChanged("no17")
				Me.Onno17Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no18", DbType:="Bit")>  _
	Public Property no18() As System.Nullable(Of Boolean)
		Get
			Return Me._no18
		End Get
		Set
			If (Me._no18.Equals(value) = false) Then
				Me.Onno18Changing(value)
				Me.SendPropertyChanging
				Me._no18 = value
				Me.SendPropertyChanged("no18")
				Me.Onno18Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no19", DbType:="Bit")>  _
	Public Property no19() As System.Nullable(Of Boolean)
		Get
			Return Me._no19
		End Get
		Set
			If (Me._no19.Equals(value) = false) Then
				Me.Onno19Changing(value)
				Me.SendPropertyChanging
				Me._no19 = value
				Me.SendPropertyChanged("no19")
				Me.Onno19Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no20", DbType:="Bit")>  _
	Public Property no20() As System.Nullable(Of Boolean)
		Get
			Return Me._no20
		End Get
		Set
			If (Me._no20.Equals(value) = false) Then
				Me.Onno20Changing(value)
				Me.SendPropertyChanging
				Me._no20 = value
				Me.SendPropertyChanged("no20")
				Me.Onno20Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no21", DbType:="Bit")>  _
	Public Property no21() As System.Nullable(Of Boolean)
		Get
			Return Me._no21
		End Get
		Set
			If (Me._no21.Equals(value) = false) Then
				Me.Onno21Changing(value)
				Me.SendPropertyChanging
				Me._no21 = value
				Me.SendPropertyChanged("no21")
				Me.Onno21Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no22", DbType:="Bit")>  _
	Public Property no22() As System.Nullable(Of Boolean)
		Get
			Return Me._no22
		End Get
		Set
			If (Me._no22.Equals(value) = false) Then
				Me.Onno22Changing(value)
				Me.SendPropertyChanging
				Me._no22 = value
				Me.SendPropertyChanged("no22")
				Me.Onno22Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no23", DbType:="Bit")>  _
	Public Property no23() As System.Nullable(Of Boolean)
		Get
			Return Me._no23
		End Get
		Set
			If (Me._no23.Equals(value) = false) Then
				Me.Onno23Changing(value)
				Me.SendPropertyChanging
				Me._no23 = value
				Me.SendPropertyChanged("no23")
				Me.Onno23Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no24", DbType:="Bit")>  _
	Public Property no24() As System.Nullable(Of Boolean)
		Get
			Return Me._no24
		End Get
		Set
			If (Me._no24.Equals(value) = false) Then
				Me.Onno24Changing(value)
				Me.SendPropertyChanging
				Me._no24 = value
				Me.SendPropertyChanged("no24")
				Me.Onno24Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no25", DbType:="Bit")>  _
	Public Property no25() As System.Nullable(Of Boolean)
		Get
			Return Me._no25
		End Get
		Set
			If (Me._no25.Equals(value) = false) Then
				Me.Onno25Changing(value)
				Me.SendPropertyChanging
				Me._no25 = value
				Me.SendPropertyChanged("no25")
				Me.Onno25Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no26", DbType:="Bit")>  _
	Public Property no26() As System.Nullable(Of Boolean)
		Get
			Return Me._no26
		End Get
		Set
			If (Me._no26.Equals(value) = false) Then
				Me.Onno26Changing(value)
				Me.SendPropertyChanging
				Me._no26 = value
				Me.SendPropertyChanged("no26")
				Me.Onno26Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no27", DbType:="Bit")>  _
	Public Property no27() As System.Nullable(Of Boolean)
		Get
			Return Me._no27
		End Get
		Set
			If (Me._no27.Equals(value) = false) Then
				Me.Onno27Changing(value)
				Me.SendPropertyChanging
				Me._no27 = value
				Me.SendPropertyChanged("no27")
				Me.Onno27Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no28", DbType:="Bit")>  _
	Public Property no28() As System.Nullable(Of Boolean)
		Get
			Return Me._no28
		End Get
		Set
			If (Me._no28.Equals(value) = false) Then
				Me.Onno28Changing(value)
				Me.SendPropertyChanging
				Me._no28 = value
				Me.SendPropertyChanged("no28")
				Me.Onno28Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no29", DbType:="Bit")>  _
	Public Property no29() As System.Nullable(Of Boolean)
		Get
			Return Me._no29
		End Get
		Set
			If (Me._no29.Equals(value) = false) Then
				Me.Onno29Changing(value)
				Me.SendPropertyChanging
				Me._no29 = value
				Me.SendPropertyChanged("no29")
				Me.Onno29Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no30", DbType:="Bit")>  _
	Public Property no30() As System.Nullable(Of Boolean)
		Get
			Return Me._no30
		End Get
		Set
			If (Me._no30.Equals(value) = false) Then
				Me.Onno30Changing(value)
				Me.SendPropertyChanging
				Me._no30 = value
				Me.SendPropertyChanged("no30")
				Me.Onno30Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no31", DbType:="Bit")>  _
	Public Property no31() As System.Nullable(Of Boolean)
		Get
			Return Me._no31
		End Get
		Set
			If (Me._no31.Equals(value) = false) Then
				Me.Onno31Changing(value)
				Me.SendPropertyChanging
				Me._no31 = value
				Me.SendPropertyChanged("no31")
				Me.Onno31Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no32", DbType:="Bit")>  _
	Public Property no32() As System.Nullable(Of Boolean)
		Get
			Return Me._no32
		End Get
		Set
			If (Me._no32.Equals(value) = false) Then
				Me.Onno32Changing(value)
				Me.SendPropertyChanging
				Me._no32 = value
				Me.SendPropertyChanged("no32")
				Me.Onno32Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no33", DbType:="Bit")>  _
	Public Property no33() As System.Nullable(Of Boolean)
		Get
			Return Me._no33
		End Get
		Set
			If (Me._no33.Equals(value) = false) Then
				Me.Onno33Changing(value)
				Me.SendPropertyChanging
				Me._no33 = value
				Me.SendPropertyChanged("no33")
				Me.Onno33Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no34", DbType:="Bit")>  _
	Public Property no34() As System.Nullable(Of Boolean)
		Get
			Return Me._no34
		End Get
		Set
			If (Me._no34.Equals(value) = false) Then
				Me.Onno34Changing(value)
				Me.SendPropertyChanging
				Me._no34 = value
				Me.SendPropertyChanged("no34")
				Me.Onno34Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no35", DbType:="Bit")>  _
	Public Property no35() As System.Nullable(Of Boolean)
		Get
			Return Me._no35
		End Get
		Set
			If (Me._no35.Equals(value) = false) Then
				Me.Onno35Changing(value)
				Me.SendPropertyChanging
				Me._no35 = value
				Me.SendPropertyChanged("no35")
				Me.Onno35Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no36", DbType:="Bit")>  _
	Public Property no36() As System.Nullable(Of Boolean)
		Get
			Return Me._no36
		End Get
		Set
			If (Me._no36.Equals(value) = false) Then
				Me.Onno36Changing(value)
				Me.SendPropertyChanging
				Me._no36 = value
				Me.SendPropertyChanged("no36")
				Me.Onno36Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no37", DbType:="Bit")>  _
	Public Property no37() As System.Nullable(Of Boolean)
		Get
			Return Me._no37
		End Get
		Set
			If (Me._no37.Equals(value) = false) Then
				Me.Onno37Changing(value)
				Me.SendPropertyChanging
				Me._no37 = value
				Me.SendPropertyChanged("no37")
				Me.Onno37Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no38", DbType:="Bit")>  _
	Public Property no38() As System.Nullable(Of Boolean)
		Get
			Return Me._no38
		End Get
		Set
			If (Me._no38.Equals(value) = false) Then
				Me.Onno38Changing(value)
				Me.SendPropertyChanging
				Me._no38 = value
				Me.SendPropertyChanged("no38")
				Me.Onno38Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no39", DbType:="Bit")>  _
	Public Property no39() As System.Nullable(Of Boolean)
		Get
			Return Me._no39
		End Get
		Set
			If (Me._no39.Equals(value) = false) Then
				Me.Onno39Changing(value)
				Me.SendPropertyChanging
				Me._no39 = value
				Me.SendPropertyChanged("no39")
				Me.Onno39Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no40", DbType:="Bit")>  _
	Public Property no40() As System.Nullable(Of Boolean)
		Get
			Return Me._no40
		End Get
		Set
			If (Me._no40.Equals(value) = false) Then
				Me.Onno40Changing(value)
				Me.SendPropertyChanging
				Me._no40 = value
				Me.SendPropertyChanged("no40")
				Me.Onno40Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no1_dblchk", DbType:="Bit")>  _
	Public Property no1_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no1_dblchk
		End Get
		Set
			If (Me._no1_dblchk.Equals(value) = false) Then
				Me.Onno1_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no1_dblchk = value
				Me.SendPropertyChanged("no1_dblchk")
				Me.Onno1_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no2_dblchk", DbType:="Bit")>  _
	Public Property no2_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no2_dblchk
		End Get
		Set
			If (Me._no2_dblchk.Equals(value) = false) Then
				Me.Onno2_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no2_dblchk = value
				Me.SendPropertyChanged("no2_dblchk")
				Me.Onno2_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no3_dblchk", DbType:="Bit")>  _
	Public Property no3_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no3_dblchk
		End Get
		Set
			If (Me._no3_dblchk.Equals(value) = false) Then
				Me.Onno3_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no3_dblchk = value
				Me.SendPropertyChanged("no3_dblchk")
				Me.Onno3_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no4_dblchk", DbType:="Bit")>  _
	Public Property no4_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no4_dblchk
		End Get
		Set
			If (Me._no4_dblchk.Equals(value) = false) Then
				Me.Onno4_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no4_dblchk = value
				Me.SendPropertyChanged("no4_dblchk")
				Me.Onno4_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no5_dblchk", DbType:="Bit")>  _
	Public Property no5_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no5_dblchk
		End Get
		Set
			If (Me._no5_dblchk.Equals(value) = false) Then
				Me.Onno5_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no5_dblchk = value
				Me.SendPropertyChanged("no5_dblchk")
				Me.Onno5_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no6_dblchk", DbType:="Bit")>  _
	Public Property no6_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no6_dblchk
		End Get
		Set
			If (Me._no6_dblchk.Equals(value) = false) Then
				Me.Onno6_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no6_dblchk = value
				Me.SendPropertyChanged("no6_dblchk")
				Me.Onno6_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no7_dblchk", DbType:="Bit")>  _
	Public Property no7_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no7_dblchk
		End Get
		Set
			If (Me._no7_dblchk.Equals(value) = false) Then
				Me.Onno7_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no7_dblchk = value
				Me.SendPropertyChanged("no7_dblchk")
				Me.Onno7_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no8_dblchk", DbType:="Bit")>  _
	Public Property no8_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no8_dblchk
		End Get
		Set
			If (Me._no8_dblchk.Equals(value) = false) Then
				Me.Onno8_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no8_dblchk = value
				Me.SendPropertyChanged("no8_dblchk")
				Me.Onno8_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no9_dblchk", DbType:="Bit")>  _
	Public Property no9_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no9_dblchk
		End Get
		Set
			If (Me._no9_dblchk.Equals(value) = false) Then
				Me.Onno9_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no9_dblchk = value
				Me.SendPropertyChanged("no9_dblchk")
				Me.Onno9_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no10_dblchk", DbType:="Bit")>  _
	Public Property no10_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no10_dblchk
		End Get
		Set
			If (Me._no10_dblchk.Equals(value) = false) Then
				Me.Onno10_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no10_dblchk = value
				Me.SendPropertyChanged("no10_dblchk")
				Me.Onno10_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no11_dblchk", DbType:="Bit")>  _
	Public Property no11_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no11_dblchk
		End Get
		Set
			If (Me._no11_dblchk.Equals(value) = false) Then
				Me.Onno11_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no11_dblchk = value
				Me.SendPropertyChanged("no11_dblchk")
				Me.Onno11_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no12_dblchk", DbType:="Bit")>  _
	Public Property no12_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no12_dblchk
		End Get
		Set
			If (Me._no12_dblchk.Equals(value) = false) Then
				Me.Onno12_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no12_dblchk = value
				Me.SendPropertyChanged("no12_dblchk")
				Me.Onno12_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no13_dblchk", DbType:="Bit")>  _
	Public Property no13_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no13_dblchk
		End Get
		Set
			If (Me._no13_dblchk.Equals(value) = false) Then
				Me.Onno13_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no13_dblchk = value
				Me.SendPropertyChanged("no13_dblchk")
				Me.Onno13_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no14_dblchk", DbType:="Bit")>  _
	Public Property no14_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no14_dblchk
		End Get
		Set
			If (Me._no14_dblchk.Equals(value) = false) Then
				Me.Onno14_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no14_dblchk = value
				Me.SendPropertyChanged("no14_dblchk")
				Me.Onno14_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no15_dblchk", DbType:="Bit")>  _
	Public Property no15_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no15_dblchk
		End Get
		Set
			If (Me._no15_dblchk.Equals(value) = false) Then
				Me.Onno15_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no15_dblchk = value
				Me.SendPropertyChanged("no15_dblchk")
				Me.Onno15_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no16_dblchk", DbType:="Bit")>  _
	Public Property no16_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no16_dblchk
		End Get
		Set
			If (Me._no16_dblchk.Equals(value) = false) Then
				Me.Onno16_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no16_dblchk = value
				Me.SendPropertyChanged("no16_dblchk")
				Me.Onno16_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no17_dblchk", DbType:="Bit")>  _
	Public Property no17_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no17_dblchk
		End Get
		Set
			If (Me._no17_dblchk.Equals(value) = false) Then
				Me.Onno17_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no17_dblchk = value
				Me.SendPropertyChanged("no17_dblchk")
				Me.Onno17_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no18_dblchk", DbType:="Bit")>  _
	Public Property no18_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no18_dblchk
		End Get
		Set
			If (Me._no18_dblchk.Equals(value) = false) Then
				Me.Onno18_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no18_dblchk = value
				Me.SendPropertyChanged("no18_dblchk")
				Me.Onno18_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no19_dblchk", DbType:="Bit")>  _
	Public Property no19_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no19_dblchk
		End Get
		Set
			If (Me._no19_dblchk.Equals(value) = false) Then
				Me.Onno19_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no19_dblchk = value
				Me.SendPropertyChanged("no19_dblchk")
				Me.Onno19_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no20_dblchk", DbType:="Bit")>  _
	Public Property no20_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no20_dblchk
		End Get
		Set
			If (Me._no20_dblchk.Equals(value) = false) Then
				Me.Onno20_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no20_dblchk = value
				Me.SendPropertyChanged("no20_dblchk")
				Me.Onno20_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no21_dblchk", DbType:="Bit")>  _
	Public Property no21_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no21_dblchk
		End Get
		Set
			If (Me._no21_dblchk.Equals(value) = false) Then
				Me.Onno21_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no21_dblchk = value
				Me.SendPropertyChanged("no21_dblchk")
				Me.Onno21_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no22_dblchk", DbType:="Bit")>  _
	Public Property no22_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no22_dblchk
		End Get
		Set
			If (Me._no22_dblchk.Equals(value) = false) Then
				Me.Onno22_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no22_dblchk = value
				Me.SendPropertyChanged("no22_dblchk")
				Me.Onno22_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no23_dblchk", DbType:="Bit")>  _
	Public Property no23_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no23_dblchk
		End Get
		Set
			If (Me._no23_dblchk.Equals(value) = false) Then
				Me.Onno23_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no23_dblchk = value
				Me.SendPropertyChanged("no23_dblchk")
				Me.Onno23_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no24_dblchk", DbType:="Bit")>  _
	Public Property no24_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no24_dblchk
		End Get
		Set
			If (Me._no24_dblchk.Equals(value) = false) Then
				Me.Onno24_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no24_dblchk = value
				Me.SendPropertyChanged("no24_dblchk")
				Me.Onno24_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no25_dblchk", DbType:="Bit")>  _
	Public Property no25_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no25_dblchk
		End Get
		Set
			If (Me._no25_dblchk.Equals(value) = false) Then
				Me.Onno25_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no25_dblchk = value
				Me.SendPropertyChanged("no25_dblchk")
				Me.Onno25_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no26_dblchk", DbType:="Bit")>  _
	Public Property no26_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no26_dblchk
		End Get
		Set
			If (Me._no26_dblchk.Equals(value) = false) Then
				Me.Onno26_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no26_dblchk = value
				Me.SendPropertyChanged("no26_dblchk")
				Me.Onno26_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no27_dblchk", DbType:="Bit")>  _
	Public Property no27_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no27_dblchk
		End Get
		Set
			If (Me._no27_dblchk.Equals(value) = false) Then
				Me.Onno27_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no27_dblchk = value
				Me.SendPropertyChanged("no27_dblchk")
				Me.Onno27_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no28_dblchk", DbType:="Bit")>  _
	Public Property no28_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no28_dblchk
		End Get
		Set
			If (Me._no28_dblchk.Equals(value) = false) Then
				Me.Onno28_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no28_dblchk = value
				Me.SendPropertyChanged("no28_dblchk")
				Me.Onno28_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no29_dblchk", DbType:="Bit")>  _
	Public Property no29_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no29_dblchk
		End Get
		Set
			If (Me._no29_dblchk.Equals(value) = false) Then
				Me.Onno29_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no29_dblchk = value
				Me.SendPropertyChanged("no29_dblchk")
				Me.Onno29_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no30_dblchk", DbType:="Bit")>  _
	Public Property no30_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no30_dblchk
		End Get
		Set
			If (Me._no30_dblchk.Equals(value) = false) Then
				Me.Onno30_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no30_dblchk = value
				Me.SendPropertyChanged("no30_dblchk")
				Me.Onno30_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no31_dblchk", DbType:="Bit")>  _
	Public Property no31_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no31_dblchk
		End Get
		Set
			If (Me._no31_dblchk.Equals(value) = false) Then
				Me.Onno31_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no31_dblchk = value
				Me.SendPropertyChanged("no31_dblchk")
				Me.Onno31_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no32_dblchk", DbType:="Bit")>  _
	Public Property no32_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no32_dblchk
		End Get
		Set
			If (Me._no32_dblchk.Equals(value) = false) Then
				Me.Onno32_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no32_dblchk = value
				Me.SendPropertyChanged("no32_dblchk")
				Me.Onno32_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no33_dblchk", DbType:="Bit")>  _
	Public Property no33_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no33_dblchk
		End Get
		Set
			If (Me._no33_dblchk.Equals(value) = false) Then
				Me.Onno33_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no33_dblchk = value
				Me.SendPropertyChanged("no33_dblchk")
				Me.Onno33_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no34_dblchk", DbType:="Bit")>  _
	Public Property no34_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no34_dblchk
		End Get
		Set
			If (Me._no34_dblchk.Equals(value) = false) Then
				Me.Onno34_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no34_dblchk = value
				Me.SendPropertyChanged("no34_dblchk")
				Me.Onno34_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no35_dblchk", DbType:="Bit")>  _
	Public Property no35_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no35_dblchk
		End Get
		Set
			If (Me._no35_dblchk.Equals(value) = false) Then
				Me.Onno35_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no35_dblchk = value
				Me.SendPropertyChanged("no35_dblchk")
				Me.Onno35_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no36_dblchk", DbType:="Bit")>  _
	Public Property no36_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no36_dblchk
		End Get
		Set
			If (Me._no36_dblchk.Equals(value) = false) Then
				Me.Onno36_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no36_dblchk = value
				Me.SendPropertyChanged("no36_dblchk")
				Me.Onno36_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no37_dblchk", DbType:="Bit")>  _
	Public Property no37_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no37_dblchk
		End Get
		Set
			If (Me._no37_dblchk.Equals(value) = false) Then
				Me.Onno37_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no37_dblchk = value
				Me.SendPropertyChanged("no37_dblchk")
				Me.Onno37_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no38_dblchk", DbType:="Bit")>  _
	Public Property no38_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no38_dblchk
		End Get
		Set
			If (Me._no38_dblchk.Equals(value) = false) Then
				Me.Onno38_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no38_dblchk = value
				Me.SendPropertyChanged("no38_dblchk")
				Me.Onno38_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no39_dblchk", DbType:="Bit")>  _
	Public Property no39_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no39_dblchk
		End Get
		Set
			If (Me._no39_dblchk.Equals(value) = false) Then
				Me.Onno39_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no39_dblchk = value
				Me.SendPropertyChanged("no39_dblchk")
				Me.Onno39_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no40_dblchk", DbType:="Bit")>  _
	Public Property no40_dblchk() As System.Nullable(Of Boolean)
		Get
			Return Me._no40_dblchk
		End Get
		Set
			If (Me._no40_dblchk.Equals(value) = false) Then
				Me.Onno40_dblchkChanging(value)
				Me.SendPropertyChanging
				Me._no40_dblchk = value
				Me.SendPropertyChanged("no40_dblchk")
				Me.Onno40_dblchkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_name1", DbType:="VarChar(50)")>  _
	Public Property name1() As String
		Get
			Return Me._name1
		End Get
		Set
			If (String.Equals(Me._name1, value) = false) Then
				Me.Onname1Changing(value)
				Me.SendPropertyChanging
				Me._name1 = value
				Me.SendPropertyChanged("name1")
				Me.Onname1Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_name2", DbType:="VarChar(50)")>  _
	Public Property name2() As String
		Get
			Return Me._name2
		End Get
		Set
			If (String.Equals(Me._name2, value) = false) Then
				Me.Onname2Changing(value)
				Me.SendPropertyChanging
				Me._name2 = value
				Me.SendPropertyChanged("name2")
				Me.Onname2Changed
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
